name: Test Reusable Workflow

on: [push, pull_request]

jobs:
  harness:
    uses: ./.github/workflows/harness-validate.yml
    with:
      project-path: .
      install-source: github
      version: main
